# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MWRlY2M2ODEzYjg3MGU3YTVmYjc2ZTY0YTI5N2QyNTU1ZDMxNTg4NDA3MTU1ZGE0OGVhNzJmOWI5YmExYmM5MDRiN2ZlNzZjNmM3NDdiOGMxNmYwOGM4MzFmMzllODNjZDBlYzAxNmVjZDEzYzViMmIyNDQwZmIwMTQyOWUzMTM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
